name: Deploy Staging to WP Engine
on:
  push:
    branches:
      - staging
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: GitHub Action Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          # Deploy vars
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: yorubasaxonstg
          # Deploy Options
          SRC_PATH: ""
          REMOTE_PATH: "wp-content/themes/yoruba-saxon/"
          PHP_LINT: TRUE
          # FLAGS: -azvr --inplace --delete --exclude=.* --exclude-from=.deployignore
          # SCRIPT: "wpe-deploy.sh"
          CACHE_CLEAR: TRUE
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Gulp Build
        run: gulp build